config/routes.rb
Rails.application.routes.draw do
  resources :poems
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
 
  resources :users, only: [:show, :index]
  resources :magnet_poems
  resources :sources
  resources :blackout_poems

  root  'welcome#index'
end

app/models/blackout_poem.rb
class BlackoutPoem < ActiveRecord::Base
  belongs_to :user
  belongs_to :blackout_poem	

  def self.prepare_text
  	source = Source.limit(1).order("RANDOM()").first
  	return source
  end
end

app/models/magnet_poem.rb
class MagnetPoem < ActiveRecord::Base
  belongs_to :user
end

app/models/poem.rb
class Poem < ActiveRecord::Base
  belongs_to :user
end

app/models/source.rb
class Source < ActiveRecord::Base
	has_many :blackout_poems
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :blackout_poems
  has_many :magnet_poems
	has_many :poems
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/blackout_poems_controller.rb
class BlackoutPoemsController < ApplicationController
  def index
  	@blackout_poems = BlackoutPoem.all
  end

  def new
  	@blackout_poem = BlackoutPoem.new
  	@source = BlackoutPoem.prepare_text
  end

  def create
     source = Source.find(params[:blackout_poem][:source_id])
     blackout_poem = source.blackout_poems.build(blackout_poem_params)
     blackout_poem.user_id = current_user.id
     if blackout_poem.save
     	redirect_to blackout_poems_path
     else
     	flash[:notice] = "Something went wrong"
     end
  end

  def destroy
  	poem = BlackoutPoem.find(params[:id])
  	poem.destroy
  	redirect_to blackout_poems_path
  end

  private
  def blackout_poem_params
  	params.require(:blackout_poem).permit(:text, :title)
 	end

end

app/controllers/magnet_poems_controller.rb
class MagnetPoemsController < ApplicationController
  def index
  	@magnet_poems = MagnetPoem.all
  end

  def new
  	@magnet_poem = MagnetPoem.new
  end

  def create
     magnet_poem = current_user.magnet_poems.build(magnet_poem_params)
     if magnet_poem.save
     	redirect_to magnet_poems_path
     else
     	flash[:notice] = "Something went wrong"
     end
  end

  def destroy
    poem = MagnetPoem.find(params[:id])
    poem.destroy
    redirect_to magnet_poems_path
  end

  private
  def magnet_poem_params
  	params.require(:magnet_poem).permit(:text, :title)
 	end
end

app/controllers/poems_controller.rb
class PoemsController < ApplicationController
  before_action :set_poem, only: [:show, :edit, :update, :destroy]

  # GET /poems
  # GET /poems.json
  def index
    @poems = Poem.all
  end

  # GET /poems/1
  # GET /poems/1.json
  def show
  end

  # GET /poems/new
  def new
    @poem = Poem.new
  end

  # GET /poems/1/edit
  def edit
  end

  # POST /poems
  # POST /poems.json
  def create
    @poem = current_user.poems.build(poem_params)
    respond_to do |format|
      if @poem.save
        format.html { redirect_to @poem, notice: 'Poem was successfully created.' }
        format.json { render :show, status: :created, location: @poem }
      else
        format.html { render :new }
        format.json { render json: @poem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /poems/1
  # PATCH/PUT /poems/1.json
  def update
    respond_to do |format|
      if @poem.update(poem_params)
        format.html { redirect_to @poem, notice: 'Poem was successfully updated.' }
        format.json { render :show, status: :ok, location: @poem }
      else
        format.html { render :edit }
        format.json { render json: @poem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /poems/1
  # DELETE /poems/1.json
  def destroy
    @poem.destroy
    respond_to do |format|
      format.html { redirect_to poems_url, notice: 'Poem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poem
      @poem = Poem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poem_params
      params.require(:poem).permit(:title, :text)
    end
end

app/controllers/sources_controller.rb
class SourcesController < ApplicationController
  def index
  	@sources = Source.all
  end

  def new
  	@source = Source.new
  end

  def create
  	source = Source.new(source_params)
  	if source.save
      redirect_to new_blackout_poem_path
    else
      redirect_to  new_source_path
    end
  end

  private
  def source_params
    params.require(:source).permit(:text)
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
def show
	@user = User.find(params[:id])
	@blackout_poems = @user.blackout_poems.order('created_at DESC')
	@magnet_poems = @user.magnet_poems.order('created_at DESC')
	@poems = @user.poems.order('created_at DESC')
end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/blackout_poems_helper.rb
module BlackoutPoemsHelper
end

app/helpers/magnet_poems_helper.rb
module MagnetPoemsHelper
end

app/helpers/poems_helper.rb
module PoemsHelper
end

app/helpers/sources_poems_helper.rb
module SourcesPoemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/blackout_poems/index.html.erb
<% @blackout_poems.each do |b| %>
	<%= b.title%><br />
	<%= b.text%><br />
	by <%= link_to b.user.username, user_path(b.user.id) %>
	<% if b.user_id == current_user.id %>
		<%= link_to 'Destroy',  blackout_poem_path(b),  method: :delete, data: { confirm: 'Are you sure?' } %>
	<% end %><br /><br />
<% end %>

app/views/blackout_poems/new.html.erb
<div style="text-align:center;"><%= link_to "See all Sources", sources_path %>&nbsp;&nbsp;<%= link_to "Add a Source", new_source_path %>&nbsp;&nbsp;<%= link_to "See all Blackout Poems", blackout_poems_path %></div>

<%= form_for(@blackout_poem) do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<%= content_tag :div, id: "text-box" do %>
  <% @source.text.split(" ").each do |s| %>
		<span><%= s %></span>
	<% end %>
<% end %>
	<%= f.hidden_field :text, id: "textarea" %>
	<%= f.hidden_field :source_id, :value => @source.id %>
	<div id="done" class="ghost-button">Done</div>
	<div id="start-over" class="ghost-button">Start Over</div>
	<%= f.submit "Submit", id: "submit", :class => 'ghost-button' %>
<% end %>

<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
<% end %>

app/views/magnet_poems/index.html.erb
<% @magnet_poems.each do |m| %>
	<%= m.title %><br />
	<%= m.text %>
	<% if m.user_id == current_user.id %>
		<%= link_to 'Destroy',  magnet_poem_path(m),  method: :delete, data: { confirm: 'Are you sure?' } %>
	<% end %><br /><br />
<% end %>

app/views/magnet_poems/new.html.erb
<div style="text-align:center;"><%= link_to "See all Magnet Poems", magnet_poems_path %></div>

 <div id="wrapper">
      <div id="header">
        <h1>Create your poem</h1>
      </div>
      <div id="content">
        <div class="draggable"> a </div>
        <div class="draggable"> or </div>
        <div class="draggable"> she </div>
        <div class="draggable"> her </div>
        <div class="draggable"> he </div>
        <div class="draggable"> his </div>
        <div class="draggable"> they </div>
        <div class="draggable"> their </div>
        <div class="draggable"> there </div>
        <div class="draggable"> story </div>
        <div class="draggable"> kiss </div>
        <div class="draggable"> in </div>
        <div class="draggable"> the </div>
        <div class="draggable"> rain </div>
        <div class="draggable"> sky </div>
        <div class="draggable"> woods </div>
        <div class="draggable"> lovely </div>
        <div class="draggable"> kind </div>
        <div class="draggable"> of </div>
        <div class="draggable"> the </div>
        <div class="draggable"> every </div>
        <div class="draggable"> and </div>
        <div class="draggable"> the </div>
        <div class="draggable"> in </div>
        <div class="draggable"> day </div>
        <div class="draggable"> night </div>
        <div class="draggable"> field </div>
        <div class="draggable"> stormy </div>
        <div class="draggable"> forever </div>
        <div class="draggable"> make </div>
        <div class="draggable"> be </div>
        <div class="draggable"> go </div>
        <div class="draggable"> and </div>
        <div class="draggable"> where </div>
        <div class="draggable"> when </div>
        <div class="draggable"> why </div>
        <div class="draggable"> who </div>
        <div class="draggable"> should </div>
        <div class="draggable"> could </div>
        <div class="draggable"> wait </div>
        <div class="draggable"> forever </div>
        <div class="draggable"> said </div>
        <div class="draggable"> she </div>
        <div class="draggable"> he </div>
        <div class="draggable"> want </div>
        <div class="draggable"> it </div>
        <div class="draggable"> leave </div>
        <div class="draggable"> smile </div>
        <div class="draggable"> go </div>
        <div class="draggable"> one </div>
        <div class="draggable"> day </div>
        <div class="draggable"> more </div>
        <div class="draggable"> on </div>
        <div class="draggable"> it </div>
        <div class="draggable"> once </div>
        <div class="draggable"> wouldn't </div>
        <div class="draggable"> be </div>
        <div class="draggable"> s </div>
        <div class="draggable"> s </div>
      </div>

      <%= form_for(@magnet_poem) do |f| %>
        <%= f.label :title %>
        <%= f.text_field :title %>
      <div id="droppable"></div>
      	<%= f.hidden_field :text, id: "magnetTextarea" %>
	    <%= f.submit "Submit", id: "magnetSubmit" %>
	<% end %>

app/views/poems/_form.html.erb
<%= form_for(@poem) do |f| %>
  <% if @poem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@poem.errors.count, "error") %> prohibited this poem from being saved:</h2>

      <ul>
      <% @poem.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/poems/edit.html.erb
<h1>Editing Poem</h1>

<%= render 'form' %>

<%= link_to 'Show', @poem %> |
<%= link_to 'Back', poems_path %>

app/views/poems/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Poems</h1>
 
    <% @poems.each do |poem| %>
       <%= link_to poem.title, poem %><br />
       <%= poem.text %><br />
       by: <%= poem.user.username %><br />
        <% if poem.user_id == current_user.id %>
         <%= link_to 'Edit', edit_poem_path(poem) %>
         <%= link_to 'Destroy', poem, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %><br />
    <% end %>

app/views/poems/new.html.erb
<div style="text-align:center;"><%= link_to 'See all Poems', poems_path %></div>
<h1>Write a Poem</h1>

<%= render 'form' %>

app/views/poems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @poem.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @poem.text %>
</p>

<p>
  <strong>Author:</strong>
  <%= link_to @poem.user.username, user_path(@poem.user.id) %>
</p>

<%= link_to 'Edit', edit_poem_path(@poem) %> |
<%= link_to 'Back', poems_path %>